---
name: FlashCut

options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  groupSortPosition: top
  bundleIdPrefix: com.flashcut

packages:
  ShortcutRecorder:
    github: Kentzo/ShortcutRecorder
    from: 3.4.0
  TOMLKit:
    github: LebJe/TOMLKit
    from: 0.6.0
  Sparkle:
    github: sparkle-project/Sparkle
    from: 2.7.0

targets:
  FlashCut:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: [FlashSpace]
    info:
      path: FlashSpace/Info.plist
      properties:
        SUPublicEDKey: hbvsYKL66p7w+2WUBbAqOvUcUNckSstWcrwTaCBwZJM=
        SUFeedURL: https://wojciechkulik.pl/FlashSpace/appcast.xml

    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_ENTITLEMENTS: FlashSpace/FlashSpace.entitlements
        DEVELOPMENT_TEAM: "${XCODE_DEVELOPMENT_TEAM}"
        ENABLE_HARDENED_RUNTIME: true
        DEAD_CODE_STRIPPING: true
        ENABLE_USER_SCRIPT_SANDBOXING: false
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: FlashCut
        INFOPLIST_KEY_NSHumanReadableCopyright: © 2025 FlashCut. All rights reserved.
      configs:
        debug:
          INFOPLIST_KEY_CFBundleDisplayName: FlashCut Dev
          PRODUCT_NAME: FlashCut-Dev
          PRODUCT_BUNDLE_IDENTIFIER: com.flashcut.FlashCut.dev

    dependencies:
      - sdk: ServiceManagement.framework
      - package: ShortcutRecorder
      - package: TOMLKit
      - package: Sparkle

    preBuildScripts:
      - name: Run SwiftLint
        script: |
          if [ "$GITHUB_ACTIONS" != "true" ]; then
            /opt/homebrew/bin/swiftlint --use-alternative-excluding
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - name: Run SwiftFormat
        script: |
          if [ "$GITHUB_ACTIONS" != "true" ]; then
            /opt/homebrew/bin/swiftformat --lint ${SRCROOT} --config .swiftformat || exit 0
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false
